### PR TITLE
[JENKINS-60798] Current context should be set

### PR DESCRIPTION
**Pull request by Vlatombe**
[JENKINS-60798](https://issues.jenkins-ci.org/browse/JENKINS-60798)

Also, only set skipTlsVerify if it is actually true

### CODE REVIEW

**Comment by maxlaverse** [comment]
Hi @Vlatombe!
I read [JENKINS-60798](https://issues.jenkins-ci.org/browse/JENKINS-60798) but I don't understand everything. The user reported that `insecure-skip-tls-verify` is not set in his kubeconfig. If `skipTlsVerify=true` is provided to the `KubernetesAuthConfig` constructor, the value should be set to `true` in the generated configuration. How does it help to not set it when it's false ?

Could it be that [this single](https://github.com/jenkinsci/kubernetes-plugin/pull/701/files#diff-440b9ecce96aa26f91c957eb465f2b36R54) line is actually the solution to the problem, by initializing `KubernetesAuthConfig` with `skipTlsVerify=true` even if `getCaCertificate()` is non null but empty ?

The change for setting the current context makes sense. Is there a way to find out if there are any other plugins than `kubernetes` and `kubernetes-cli` that use `kubernetes-credentials` ? If so I would check if this change of default can break anything.

**Comment by Vlatombe** [comment]
Hi @maxlaverse, I think there were two issues:

* Missing current context (this PR). This was done previously in the cli based impl (https://github.com/jenkinsci/kubernetes-plugin/blob/f6590b36b269f99f0ef9add3950161bafdb960fc/src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubectlBuildWrapper.java#L184)
* empty/null handling of caCertificate on upgrade (https://github.com/jenkinsci/kubernetes-plugin/pull/701)

**Comment by maxlaverse** [comment]
Alright ! I'm not convinced by the reason to change the `skipTlsVerify` change but I don't think it will hurt.

**Comment by maxlaverse** [comment]
Released in 0.6.1 @Vlatombe

**Comment by Vlatombe** [comment]
@maxlaverse Thanks! Though I don't see 0.6.1 in artifactory yet. And the git history looks strange, the release commit is missing.

**Comment by maxlaverse** [comment]
I must have messed something up :/
Since I don't have my laptop to check the local state, I just released another minor version:
```
    [INFO] --- maven-deploy-plugin:2.8.2:deploy (default-deploy) @ kubernetes-credentials ---
    Uploading to maven.jenkins-ci.org: https://repo.jenkins-ci.org/releases/org/jenkinsci/plugins/kubernetes-credentials/0.6.2/kubernetes-credentials-0.6.2.hpi
    Uploaded to maven.jenkins-ci.org: https://repo.jenkins-ci.org/releases/org/jenkinsci/plugins/kubernetes-credentials/0.6.2/kubernetes-credentials-0.6.2.hpi (34 kB at 22 kB/s)
[...]
```

**Pull request merged**
